"""
File storage utilities for document uploads.

Centralizes: filename sanitization, allowed-type/size validation,
SHA-256 hashing, and disk persistence. Kept separate from the router
and service layers so swapping local disk for S3/Azure Blob later
(mentioned in the spec's "Deployment Ready" goals) only requires
changing this module.
"""
import hashlib
import os
import uuid
from pathlib import Path

from app.core.config import settings
from app.core.exceptions import FileProcessingException

# Matches Phase 4's OCR input spec (PDF / PNG / JPG) exactly, so nothing
# can be uploaded in Phase 3 that the OCR pipeline won't later be able
# to process.
ALLOWED_MIME_TYPES = {
    "application/pdf": ".pdf",
    "image/png": ".png",
    "image/jpeg": ".jpg",
}


def get_upload_dir() -> Path:
    upload_dir = Path(settings.UPLOAD_DIR)
    upload_dir.mkdir(parents=True, exist_ok=True)
    return upload_dir


def validate_upload(*, filename: str, content_type: str, size_bytes: int) -> str:
    """
    Validate an incoming upload against allowed types and the configured
    size limit. Returns the canonical file extension for the detected
    mime type. Raises FileProcessingException on any violation.
    """
    if content_type not in ALLOWED_MIME_TYPES:
        raise FileProcessingException(
            f"Unsupported file type '{content_type}'. Allowed types: "
            f"{', '.join(ALLOWED_MIME_TYPES.keys())}",
            details={"received_content_type": content_type},
        )

    if size_bytes <= 0:
        raise FileProcessingException("Uploaded file is empty")

    if size_bytes > settings.max_upload_size_bytes:
        raise FileProcessingException(
            f"File exceeds the maximum allowed size of {settings.MAX_UPLOAD_SIZE_MB}MB",
            details={"size_bytes": size_bytes, "max_bytes": settings.max_upload_size_bytes},
        )

    if not filename or not filename.strip():
        raise FileProcessingException("Filename is required")

    return ALLOWED_MIME_TYPES[content_type]


def generate_stored_filename(extension: str) -> str:
    """
    Generate a collision-proof, path-traversal-proof filename for disk
    storage. The original user-supplied filename is never used as the
    on-disk name -- only stored as metadata in the database.
    """
    return f"{uuid.uuid4().hex}{extension}"


def compute_sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def save_file(content: bytes, stored_filename: str) -> str:
    """Write file content to disk and return the absolute path written."""
    upload_dir = get_upload_dir()
    destination = upload_dir / stored_filename

    # Defensive check: stored_filename is always generated by
    # generate_stored_filename(), never derived from user input, but we
    # verify the resolved path stays inside upload_dir as a second layer
    # of protection against path traversal.
    resolved = destination.resolve()
    if upload_dir.resolve() not in resolved.parents and resolved != upload_dir.resolve():
        raise FileProcessingException("Resolved file path escapes the upload directory")

    with open(destination, "wb") as f:
        f.write(content)

    return str(destination)


def delete_file_from_disk(stored_filename: str) -> None:
    """Remove a file from disk. Silently no-ops if it doesn't exist."""
    upload_dir = get_upload_dir()
    path = upload_dir / stored_filename
    if path.exists():
        os.remove(path)


def get_file_path(stored_filename: str) -> Path:
    return get_upload_dir() / stored_filename


def get_intake_dir() -> Path:
    intake_dir = Path(settings.INTAKE_SCAN_DIR)
    intake_dir.mkdir(parents=True, exist_ok=True)
    return intake_dir


def resolve_intake_subpath(subpath: str | None) -> Path:
    """
    Resolve an optional client-supplied relative subpath against the
    configured intake root, guaranteeing the result can never escape
    that root.

    `subpath` is never treated as an absolute path and never allowed to
    contain '..' segments that would walk outside INTAKE_SCAN_DIR --
    this is the only thing standing between "scan a configured staging
    folder" (intended) and "read arbitrary files off the server's
    disk" (a real vulnerability if this check were missing), since the
    folder-scan endpoint exists specifically to let the API read from
    the filesystem rather than from request bodies.
    """
    intake_root = get_intake_dir().resolve()

    if not subpath or not subpath.strip():
        return intake_root

    candidate = (intake_root / subpath).resolve()

    if intake_root != candidate and intake_root not in candidate.parents:
        raise FileProcessingException(
            "Resolved scan path escapes the configured intake directory",
            details={"intake_root": str(intake_root)},
        )

    return candidate


def list_intake_files(scan_dir: Path) -> list[Path]:
    """
    List files directly within scan_dir whose extension matches an
    allowed upload type. Non-recursive by design -- a folder-scan
    intake is meant for "drop files in this staging folder," not for
    walking an arbitrary directory tree, which would make the
    MAX_BULK_INTAKE_FILES ceiling much harder to reason about.
    """
    if not scan_dir.exists():
        raise FileProcessingException(f"Intake directory does not exist: {scan_dir}")
    if not scan_dir.is_dir():
        raise FileProcessingException(f"Intake path is not a directory: {scan_dir}")

    allowed_extensions = set(ALLOWED_MIME_TYPES.values())
    return sorted(
        p for p in scan_dir.iterdir()
        if p.is_file() and p.suffix.lower() in allowed_extensions
    )


def detect_mime_type(extension: str) -> str:
    """Reverse lookup: canonical extension -> mime type, for files read from disk
    (which have no client-supplied Content-Type to trust)."""
    for mime_type, ext in ALLOWED_MIME_TYPES.items():
        if ext == extension.lower():
            return mime_type
    raise FileProcessingException(f"Unsupported file extension '{extension}'")
