"""
Markdown Table Parser for PaddleOCR-VL Output.

Extracts structured invoice line items directly from pipe-delimited Markdown tables
natively generated by PaddleOCR-VL.

DO NOT USE spatial intervals, x/y coordinates, bounding boxes, or row clustering.
This parser is a deterministic in-memory transformation layer from Markdown table
representation to Python structured data for downstream extraction consumption.
"""
import re
from typing import Any, Dict, List, Optional, Tuple


# Synonym mapping for table column header recognition
HEADER_COLUMN_MAP = {
    "item_number": [
        "item_number", "item no", "item #", "no.", "no_", "no", "sl no", "sr no",
        "pos", "pos.", "pos no", "item", "article", "art.", "sr.", "sl.", "#"
    ],
    "description": [
        "description", "item description", "particulars", "product", "items",
        "designation", "bezeichnung", "artikel", "details", "product description",
        "specification", "service"
    ],
    "quantity": ["qty", "quantity", "menge", "anzahl", "qty.", "menge (stk)", "count"],
    "unit": ["unit", "uom", "um", "einheit", "u/m", "measure", "unit of measure"],
    "unit_price": [
        "unit price", "net price", "price", "rate", "preis", "einzelpreis",
        "netto-preis", "unit cost", "price/unit", "price (net)", "rate/unit"
    ],
    "net_amount": [
        "net amount", "net worth", "taxable amount", "taxable value", "betrag",
        "nettobetrag", "net", "total net", "base amount", "net price total",
        "amount"
    ],
    "vat_rate": [
        "vat [%]", "vat[%]", "vat %", "vat%", "tax %", "tax%", "gst %", "gst%",
        "mwst", "mwst%", "mwst %", "vat rate", "tax rate", "rate %", "mwst. %",
        "vat", "mwst.", "tax rate %", "gst"
    ],
    "gross_amount": [
        "gross amount", "gross worth", "total amount", "gross total", "line total",
        "gesamt", "bruttobetrag", "brutto", "gross", "total"
    ],
}

# Compile a global list of (synonym, col_name) sorted by length descending
ALL_SYNONYMS: List[Tuple[str, str]] = []
for col_name, synonyms in HEADER_COLUMN_MAP.items():
    for syn in synonyms:
        ALL_SYNONYMS.append((syn.lower().strip(), col_name))
ALL_SYNONYMS.sort(key=lambda x: len(x[0]), reverse=True)


def _match_column_name(header_text: str) -> Optional[str]:
    """Map a raw Markdown table header cell to a standardized field name."""
    clean = re.sub(r"[^\w%#]", " ", header_text.lower()).strip()
    clean = re.sub(r"\s+", " ", clean)
    if not clean:
        return None

    # 1. Exact match first
    for syn, col_name in ALL_SYNONYMS:
        if clean == syn:
            return col_name

    # 2. Token boundary match (longest synonym first)
    clean_padded = f" {clean} "
    for syn, col_name in ALL_SYNONYMS:
        # Don't match short single-word tokens inside larger phrases carelessly
        if len(syn) >= 3 and f" {syn} " in clean_padded:
            return col_name

    return None


def parse_markdown_table(text: str) -> Dict[str, Any]:
    """
    Parses Markdown tables from text (such as PaddleOCR-VL full_text output)
    into a structured table representation.

    Returns:
        Dict[str, Any] with keys:
            headers: list of recognized column names
            columns: dict of column mappings
            line_items: list of line item dicts
            line_items_count: int
    """
    if not text or not text.strip():
        return {
            "headers": [],
            "columns": {},
            "line_items": [],
            "line_items_count": 0,
        }

    lines = [line.strip() for line in text.splitlines()]
    
    # Locate table block: consecutive lines with pipe separators
    table_lines: List[str] = []
    in_table = False

    for line in lines:
        if line.startswith("|") and line.endswith("|") and line.count("|") >= 3:
            table_lines.append(line)
            in_table = True
        elif in_table:
            # Table ended
            if len(table_lines) >= 3:  # Header + separator + at least one data row
                break
            else:
                table_lines = []
                in_table = False

    if len(table_lines) < 2:
        return {
            "headers": [],
            "columns": {},
            "line_items": [],
            "line_items_count": 0,
        }

    # Extract header line and divider line
    header_line = table_lines[0]
    raw_headers = [c.strip() for c in header_line.split("|")[1:-1]]

    # Map headers to canonical field names
    col_mapping: Dict[int, str] = {}
    for idx, hdr in enumerate(raw_headers):
        col_name = _match_column_name(hdr)
        if col_name and col_name not in col_mapping.values():
            col_mapping[idx] = col_name

    # Determine start of data rows (skip divider row like |---|---|)
    start_row_idx = 1
    if len(table_lines) > 1:
        second_line = table_lines[1]
        divider_cells = [cell.strip() for cell in second_line.split("|")[1:-1] if cell.strip()]
        if divider_cells and all(re.match(r"^:?-+:?$", cell) for cell in divider_cells):
            start_row_idx = 2

    line_items: List[Dict[str, Any]] = []

    for row_idx, row_str in enumerate(table_lines[start_row_idx:], start=1):
        cells = [c.strip() for c in row_str.split("|")[1:-1]]
        if not any(cells):
            continue

        item_dict: Dict[str, Any] = {
            "item_number": None,
            "description": "",
            "quantity": None,
            "unit": None,
            "unit_price": None,
            "net_amount": None,
            "vat_rate": None,
            "gross_amount": None,
            "confidence": 1.0,
            "raw_blocks": [],
        }

        # Assign values by mapped column index
        for c_idx, cell_val in enumerate(cells):
            if not cell_val:
                continue
            if c_idx in col_mapping:
                mapped_col = col_mapping[c_idx]
                item_dict[mapped_col] = cell_val
            elif not item_dict["description"]:
                # If unmapped and description is empty, assign text to description
                item_dict["description"] = cell_val

        # If no item_number was assigned, default to row index
        if not item_dict["item_number"]:
            item_dict["item_number"] = str(row_idx)

        # Check if the row contains substantive financial or item information
        has_substance = bool(item_dict["description"]) or any(
            item_dict.get(k) for k in ["quantity", "unit_price", "net_amount", "gross_amount"]
        )
        if has_substance:
            line_items.append(item_dict)

    return {
        "headers": [col_mapping.get(i, f"col_{i}") for i in range(len(raw_headers))],
        "columns": {col_mapping.get(i, f"col_{i}"): {"index": i} for i in range(len(raw_headers)) if i in col_mapping},
        "line_items": line_items,
        "line_items_count": len(line_items),
    }
