"""add pgvector, document_chunks, and vendor_knowledge tables

Revision ID: 018069fabf68
Revises: b9c2ae51cb79
Create Date: 2026-08-31 11:12:34.783033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = '018069fabf68'
down_revision: Union[str, Sequence[str], None] = 'b9c2ae51cb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Only create pgvector extension when using PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('vendor_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_code', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('default_gl_account', sa.String(length=30), nullable=True),
    sa.Column('default_cost_center', sa.String(length=30), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_knowledge_vendor_code'), 'vendor_knowledge', ['vendor_code'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_type'), 'document_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('company_code', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('vendor_code', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('validation_status', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_documents_company_code'), 'documents', ['company_code'], unique=False)
    op.create_index(op.f('ix_documents_validation_status'), 'documents', ['validation_status'], unique=False)
    op.create_index(op.f('ix_documents_vendor_code'), 'documents', ['vendor_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_vendor_code'), table_name='documents')
    op.drop_index(op.f('ix_documents_validation_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_code'), table_name='documents')
    op.drop_column('documents', 'validation_status')
    op.drop_column('documents', 'vendor_code')
    op.drop_column('documents', 'company_code')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_type'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_vendor_knowledge_vendor_code'), table_name='vendor_knowledge')
    op.drop_table('vendor_knowledge')
    op.drop_table('system_setting')
    # ### end Alembic commands ###
